### ISSUE TITLE
企业微信登录问题

### ISSUE THREAD

**Issue by kid88888** [Houvven/I-Am-Pad#1]
在备用机上安装了该模块后，虽然可以出现平板登录的选项，但是扫码登录后会顶号，不是同时在线的，企业微信会检测系统的dp，只有超过480才能同时保持在线。

我之前一直是备用机改系统dp为480 平板登录的。

**Comment by Houvven** [comment]
测试了一下，两台手机，harmonyos(phone)+Android(伪装成平板)，可以同时在线。不过退出重新进去不行，看了是热修复的原因。

**Comment by Houvven** [comment]
试试这个 https://drive.google.com/file/d/1VEulJVNEw5KYzpyMifQ6x_4eF4tYr5ZQ/view?usp=drive_link
