### ISSUE TITLE
能否支持粤政易

### ISSUE THREAD

**Issue by Cheukfung** [Houvven/I-Am-Pad#2]
能否支持粤政易（前身政务微信，应该和企业微信很大关系）

**Comment by Houvven** [comment]
这个有平板登录模式吗

**Comment by Cheukfung** [comment]
> 这个有平板登录模式吗，看了下和企业微信差不多，不过没搜到平板登录相关的resource

我没有安卓平板，但是在ipad上有平板模式

**Comment by Houvven** [comment]
> > 这个有平板登录模式吗，看了下和企业微信差不多，不过没搜到平板登录相关的resource
> 
> 我没有安卓平板，但是在ipad上有平板模式

是有平板登录单btn吗

**Comment by Cheukfung** [comment]
> > > 这个有平板登录模式吗，看了下和企业微信差不多，不过没搜到平板登录相关的resource
> > 
> > 
> > 我没有安卓平板，但是在ipad上有平板模式
> 
> 是有平板登录的btn吗，多设备登录？

在iPad上，可以选仅在此设备登录，或者手机平板共同登录，共同登录就变成扫码，和微信的平板模式一样的逻辑

**Comment by Houvven** [comment]
> > > > 这个有平板登录模式吗，看了下和企业微信差不多，不过没搜到平板登录相关的resource
> > > 
> > > 
> > > 我没有安卓平板，但是在ipad上有平板模式
> > 
> > 
> > 是有平板登录的btn吗，多设备登录？
> 
> 在iPad上，可以选仅在此设备登录，或者手机平板共同登录，共同登录就变成扫码，和微信的平板模式一样的逻辑

安卓端貌似把平板登录删掉了😦

**Comment by Cheukfung** [comment]
请问有支持的计划吗

**Comment by Houvven** [comment]
> 请问有支持的计划吗

有 过两天吧 租的房子还没牵网线

**Comment by ldp666** [comment]
安卓没有找到平板登录😂

**Comment by Cheukfung** [comment]
经过实体机安卓平板测试，是有入口的

**Comment by Houvven** [comment]
> 安卓没有找到平板登录😂

有啊 我都开出来了 不过没账号测不了

**Comment by Houvven** [comment]
> 经过实体机安卓平板测试，是有入口的

可以pr一下 这几天没空搞 主机还没装好
