### ISSUE TITLE
小米8 lite无法使用

### ISSUE THREAD

**Issue by xiadanyouling** [Houvven/I-Am-Pad#3]
小米8lite版 点击之后没有跳出“作为平板或者手机使用”的界面，点击登录按钮后也没有显示出“作为平板登录”的按钮，系统版本是miui 12.5.2安卓10

**Comment by Houvven** [comment]
> 另外一台小米8就能完美使用....不知道问题出在哪

amazing。有空了我换个实现方式。

**Comment by xairt** [comment]
> > 另外一台小米8就能完美使用....不知道问题出在哪
> 
> amazing。有空了我换个实现方式。

发现可以直接配合lspatch嵌入到微信里，此后直接安装就能用。实在是太感谢了！！！！！！！！

**Comment by Dylan-Li8** [comment]
我的是VIVO X200，微信版本是8.0.49，使用lspatch免root方式，也是没办法打开平板模式

**Comment by kid88888** [comment]
安装该模块后，要清除应用数据才会出现平板入口。

**Comment by Dylan-Li8** [comment]
> 安装该模块后，要清除应用数据才会出现平板入口。

@kid88888 已经清理缓存了，但是一直没有出来入口。

**Comment by kid88888** [comment]
> > 安装该模块后，要清除应用数据才会出现平板入口。
> 
> @kid88888 已经清理缓存了，但是一直没有出来入口。

是清除数据

**Comment by Dylan-Li8** [comment]
> > > 安装该模块后，要清除应用数据才会出现平板入口。
> > 
> > 
> > @kid88888 已经清理缓存了，但是一直没有出来入口。
> 
> 是清除数据

@kid88888 数据也清过了，试了好几次了。唯一不确定的变量是我改了包名，因为不想卸载原来的官方微信，不知道这有没有影响。

**Comment by kid88888** [comment]
> > > > 安装该模块后，要清除应用数据才会出现平板入口。
> > > 
> > > 
> > > @kid88888 已经清理缓存了，但是一直没有出来入口。
> > 
> > 
> > 是清除数据
> 
> @kid88888 数据也清过了，试了好几次了。唯一不确定的变量是我改了包名，因为不想卸载原来的官方微信，不知道这有没有影响。

模块就是识别包名的，改包名识别不出来，我有点没搞懂你这使用方法，开平板模式不是给备用机用的吗，改包名干嘛？双开也可以啊

**Comment by Dylan-Li8** [comment]
> > > > > 安装该模块后，要清除应用数据才会出现平板入口。
> > > > 
> > > > 
> > > > @kid88888 已经清理缓存了，但是一直没有出来入口。
> > > 
> > > 
> > > 是清除数据
> > 
> > 
> > @kid88888 数据也清过了，试了好几次了。唯一不确定的变量是我改了包名，因为不想卸载原来的官方微信，不知道这有没有影响。
> 
> 模块就是识别包名的，改包名识别不出来，我有点没搞懂你这使用方法，开平板模式不是给备用机用的吗，改包名干嘛？双开也可以啊

新手机不能root的情况下，直接用lspatch修改版的话，很多应用没办法使用微信登录，也没法分享。那么我就在保留官方微信的前提下，装一个有模块的版本，以平板方式登录，就可以愉快使用带模块的微信，而不影响微信功能了。

**Comment by Dylan-Li8** [comment]
@Houvven 如果可以将匹配包名改成匹配com.tencent.mm前缀就好，例如com.tencent.mm1、com.tencent.mm2都可以加载

**Comment by Dylan-Li8** [comment]
我自己魔改了一下，直接硬编码我改的包名，但是用Actions编译的时候失败了

**Comment by Houvven** [comment]
> @Houvven 如果可以将匹配包名改成匹配com.tencent.mm前缀就好，例如com.tencent.mm1、com.tencent.mm2都可以加载

改了

**Comment by xiadanyouling** [comment]
破案了，就是没有清除应用数据造成的，在设置里面清除应用数据（不是清除应用缓存！）重进就能看到“作为平板使用”的界面了！赞美作者大大！
