### ISSUE TITLE
8.0.53版本提示环境异常

### ISSUE THREAD

**Issue by 251623126** [Houvven/I-Am-Pad#4]
微信登录环境存在异常。为了账号安全，本次登录已失效。是版本问题还是直接无视就好

**Comment by Houvven** [comment]
你是修补的还是用的lsposed

**Comment by 251623126** [comment]
> 你是修补的还是用的lsposed

没有修补，纯lsposed模块，昨天晚上挂的，今天早上被异常退出登录了

**Comment by axnir** [comment]
一样的情况，晚上登录，第二天凌晨就掉线了

**Comment by 251623126** [comment]
又使用了一段时间稳定使用 环境异常可能跟号也有关系
