### ISSUE TITLE
请教下大佬这个模块支持钉钉吗

### ISSUE THREAD

**Issue by adll123** [Houvven/I-Am-Pad#8]

**Comment by Houvven** [comment]
see https://github.com/Houvven/I-Am-Pad/commit/ede4568b2d5301aa7287d8aedbcff7c0aa0dbe3c

**Comment by adll123** [comment]
> see [ede4568](https://github.com/Houvven/I-Am-Pad/commit/ede4568b2d5301aa7287d8aedbcff7c0aa0dbe3c)

感谢回复，但我在手机上测试不支持，安卓11，钉钉版本6.5.20

**Comment by adll123** [comment]
大佬能否指点下，是钉钉版本的问题吗
